export const SAVE_CARTLIST = "SAVE_CARTLIST";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DO_SHOPPING = 'DO_SHOPPING';